name: Zber pocasia
on:
  schedule:
    - cron: '0 22 * * *' 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozitara
        uses: actions/checkout@v3
      - name: Instalacia kniznic
        run: pip install pandas requests
      - name: Spustenie skriptu
        run: python main.py
      - name: Ulozenie zmien
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add weather_daily.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Aktualizacia denneho priemeru" && git push)
